nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
        hosts: ['^api\.']
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['*'] # En desarrollo, permitimos todo. En prod, especificar los dominios.
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE']
            max_age: 3600
            hosts: ['^localhost$']